apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy-service
  name: reverseproxy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy-service
  template:
    metadata:
      labels:
        service: reverseproxy-service
    spec:
      containers:
      - image: xeusteerapat/reverseproxy-service
        name: reverseproxy-service
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always