apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels:
    service: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: users-service
  template:
    metadata:
      labels:
        service: users-service
    spec:
      containers:
      - name: users-service
        image: xeusteerapat/users-service
        imagePullPolicy: Always        
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
      restartPolicy: Always
      